<div class="container">
	<div class="row">
		<div class="panel panel-info">
			<div class="panel-heading">
			<h3 class="panel-title"><?=$comTitle?>créé le <?=$comCreaDate?>, modifié le <?=$comModifDate?>  par <?=$comAuthor?></h3>
			</div>
			<div class="panel-body">
			    <?=$comContent?>
			</div>
			<div class="panel-footer">
				<form action="" method="POST" class="comment">
					<div class="comment-item">
						<label for="title">Titre du commentaire</label>
						<input type="text" name="title" id="title">
					</div>
					<div class="comment-item">
						<label for="content">Votre commentaire</label>
						<textarea type="text" name="content" id="content"></textarea>
					</div>	
					<button type="submit">Créer</button>
				</form>
			</div>
		</div>
	</div>
</div>