
<!--Affichage de l'article-->
<div class="container">
	<div class="row">
		<div class="panel panel-info">
			<div class="panel-heading">
			<h3 class="panel-title"><?=$artTitle?>créé le <?=$artCreaDate?> par <?=$artAuthor?></h3>
			</div>
			<div class="panel-body">
			    <?=$artContent?>
			</div>
		</div>
	</div>
</div>
<!-- Affichage des commentaires liés à l'article -->
<div class="container">
	<h3>Commentaires</h3>
	<?php require('apps/artComment.php'); ?>
	<div class="container">
		<div class="row">
			<div class="col-sm-12 comment-body">
				<p><?=$noComment?></p>
			</div>
		</div>
	</div>
</div>

<div class="boutonComment">
<a href="?page=artComment.php">Commenter</a>
</div>