<h2>Modification d'un article</h2>

<form action="" method="POST" class="article">
	<div class="article-item">
		<label for="title">Titre de l'article</label>
		<input type="text" name="title" id="title" value="<?=$artTitle?>">
	</div>
	<div class="article-item">
		<label for="content">Contenu de l'article</label>
		<textarea type="text" name="content" id="content" value="<?=$artContent?>"></textarea>
	</div>
	
	<button type="submit">Confirmer les modifications</button>

</form>