
<!--Affichage de l'article-->
<div class="container">
	<div class="row">
		<div class="panel panel-info">
			<div class="panel-heading">
			<h3 class="panel-title"><?=$artTitle?>créé le <?=$artCreaDate?> par <?=$artAuthor?></h3>
			</div>
			<div class="panel-body">
			    <?=$artContent?>
			</div>
		</div>
	</div>
</div>
<!-- Affichage des commentaires liés à l'article -->
<?php require ("apps/artComment.php"); ?>
	

