
<!--Affichage de l'article-->

<div class="container">
	<div class="row">
		<div class="panel panel-info">
			<div class="panel-heading">
			<h3 class="panel-title"><?=$artTitle?>créé le <?=$artCreaDate?> par <?=$artAuthor?></h3>
			<!-- <form action="" method="get" class="comment">
				<a href="?page=artCommentCrea&artId=<?=$artId?>">
					<button type="submit" nom="bouton_creer_com">Ajouter un commentaire</button>
				</a>
			</form> -->
			</div>
			<div class="panel-body">
			    <?=$artContent?>
			</div>
		</div>

		<?php
		require('apps/btn_ajoute_com.php');
		?>



	</div>
</div>
<!-- Affichage des commentaires liés à l'article -->
<?php 
require ("apps/artComment.php"); 
// var_dump($artId);

?>
	

