<h2>Création d'un article</h2>

<div class="error">Erreur : pour visu mais à enlever du phtml</div>

<form action="" method="POST" class="article">
	<div class="article-item">
		<label for="title">Titre de l'article</label>
		<input type="text" name="title" id="title">
	</div>
	<div class="article-item">
		<label for="content">Contenu de l'article</label>
		<textarea type="text" name="content" id="content"></textarea>
	</div>
	
	<button type="submit">Créer</button>

</form>