<header>

	<nav class="navbar navbar-inverse">
		<div class="container-fluid">
			<ul class="nav navbar-nav">
				<li class="active"> <a href="index.php?page=login">Se connecter</a> </li>
				<li> <a href="index.php?page=register">S'inscrire</a> </li>
			</ul>
		</div>
	</nav>
	<div class="messageAccueil">
		<h1>Bienvenue sur POISSON ROUGE</h1>
		<h2>votre application de gestion des tâches</h2>
	</div>

</header>