<header>

	<h1>Bienvenue sur POISSON ROUGE votre application de gestion des tâches</h1>

	<nav class="navbar navbar-inverse">
		<div class="container-fluid">
			<ul class="nav navbar-nav">
				<li class="active"> <a href="index.php">Home</a> </li>
				<li> <a href="index.php?page=create">Créer une tâche</a> </li>
				<li> <a href="index.php?page=logout">Se déconnecter</a> </li>
			</ul>
		</div>
	</nav>

</header>