<header>

	<h1>Bienvenue sur le blog des 4</h1>
	<h2>Page administrateur</h2>

	<nav class="navbar navbar-inverse">
		<div class="container-fluid">
			<ul class="nav navbar-nav">
				<li class="active"> <a href="index.php">Home</a> </li>
				<li> <a href="index.php?page=create_admin">Créer un article</a> </li>
				<li> <a href="index.php?page=logout">Se déconnecter</a> </li>
			</ul>
		</div>
	</nav>

</header>