

<a href="?page=article&artId=<?=$artId?>&id_author=<?=$id_author?>">

	<div class="panel panel-info">
			<div class="panel-primary">
			  	<!-- <a href="?page=article.php&artId=<?=$artId?>"> -->
			    <h3 class="panel-title">
			    	<?=$artTitle?>
					créé par <?=$artAuthor?> le <?=$artCreaDate?>
			    </h3>
			</div>
			<div class="panel-body">
			    <?=$artContent?> ....... <em>(lire la suite)</em>
			</div>
              
			
<a href="index.php?page=login&action=supprimer&id=<?php $artId ?>">supprimer</a>
<a href="index.php?page=login&action=modifier&id=<?php $artId ?>">modiffier</a>

	</div>
</a>
