
<a href="?page=article&artId=<?=$artId?>">

	<div class="panel panel-primary">
			<div class="panel-heading">
			  	<!-- <a href="?page=article.php&artId=<?=$artId?>"> -->
			    <h3 class="panel-title">
			    	<?=$artTitle?>
					créé par <?=$artAuthor?> le <?=$artCreaDate?>
			    </h3>
			</div>
			<div class="panel-body">
			    <?=$artContent?> ....... <em>(lire la suite)</em>
			</div>
              
		  
    </div>
	

</a>
