
<form action="" method="POST" class="register">
<table style="border:2px dashed #FF9809 ">
	<tr>
         <td style="background-color:#EE9533" colspan="2"><h3><strong>Inscription</strong></h3></td>
	</tr>
    <tr>
	
		<td><label for="nom">nom</label></td>
		<td><input type="text" name="nom" id="firstName"></td>
    </tr>
    <tr>
		<td><label for="prenom"></label>prenom</td>
		<td><input type="text" name="prenom" id="surname"/></td>
    </tr>
    <tr>
		<td><label for="mail">Email</label></td>
		<td><input type="email" name="mail" id="mail"></td>
    </tr>
    <tr>
		<td><label for="login">Nom d'utilisateur</label></td>
		<td><input type="text" name="login" id="login"></td>
    </td>
    <tr>
		<td><label for="pwd">Mot de passe</label></td>
		<td><input type="password" name="pwd" id="pass"></td>
    </tr>
    <tr>
		<td><label for="pwd2">Confirmez le mot de passe</label></td>
		<td><input type="password" name="pwd2" id="passConfirm"></td>
    </tr>
</table>
	<button type="submit">S'inscrire</button>

</form>

