<h2>Inscription</h2>
<div class="error">hello</div>
<form action="" method="POST" class="register">
<table>
    <tr>
	
		<td><label for="firstName">nom</label></td>
		<td><input type="text" name="nom" id="firstName"></td>
    </tr>
    <tr>
		<td><label for="surname"></label>prenom</td>
		<td><input type="text" name="prenom" id="surname"/></td>
    </tr>
    <tr>
		<td><label for="mail">Email</label></td>
		<td><input type="email" name="mail" id="mail"></td>
    </tr>
    <tr>
		<td><label for="login">Nom d'utilisateur</label></td>
		<td><input type="text" name="login" id="login"></td>
    </td>
    <tr>
		<td><label for="pass">Mot de passe</label></td>
		<td><input type="password" name="pwd" id="pass"></td>
    </tr>
    <tr>
		<td><label for="passConfirm">Confirmez le mot de passe</label></td>
		<td><input type="password" name="pwd2" id="passConfirm"></td>
    </tr>
</table>
	<button type="submit">S'inscrire</button>

</form>

