<!DOCTYPE HTML>
<html>
	<head>
		<title>Le blog des 4</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
		<link rel="stylesheet" href="./public/styles/style.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
		<script src="./public/js/script.js"></script>
		<script>
		/*$('document').ready(function()
		{
			alert('a');
		});*/
		</script>
	</head>
	<body>
		<?php require('apps/header.php'); ?>
		<?php require('apps/content.php'); ?>
		<?php require('apps/footer.php'); ?>
  	</body>
</html>